# Generated by Django 2.2.1 on 2019-06-20 12:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.FileField(upload_to='uploads/shedules')),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('group_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Group')),
            ],
        ),
    ]
